version: 2

jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps:focal-curl"
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: |
                  sudo apt update
                  sudo apt install -y gcc g++ cmake pkg-config uuid uuid-dev uuid-runtime libantlr4-runtime4.8 ctest
                  git clone https://github.com/catchorg/Catch2.git
                  cd Catch2
                  cmake -Bbuild -H. -DBUILD_TESTING=OFF
                  sudo cmake --build build/ --target install
                  cd ..
                  mkdir antlr
                  cd antlr
                  curl https://www.antlr.org/download/antlr4-cpp-runtime-4.8-source.zip --output antlr.zip
                  unzip antlr.zip
                  mkdir build && mkdir run && cd build
                  cmake ..
                  make
                  sudo make install
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Point Unit Testing
          command: |
              cd test
              ctest