version: 2

jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps:focal-curl"
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
                  sudo apt update
                  sudo apt install -y gcc g++ cmake pkg-config uuid uuid-dev uuid-runtime libantlr4-runtime4.8 libantlr4-runtime-dev libgtest-dev
      - run:
          name: Install required libraries
          command: 'sudo cp third_party/fp_ip_cmodel/lib/* /usr/lib'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild -DBUILD_TESTS=True'
      - run:
          name: Build antlr runtime
          command: 'cmake --build build --target parsers'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Point Unit Testing
          command: |
              cd build/test
              mkdir test-reports
              ./test_target --gtest_output="xml:test-reports/report.xml"
      - store_test_results:
          path: ~/project/build/test/test-reports
